name: Deploy Hexo Site

on:
  push:
    branches:
      - main  # 假设您的源文件在 'main' 分支上
  workflow_dispatch:  # 允许手动触发工作流程

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: npm install

    - name: Generate Static Files
      run: npx hexo generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        repository: Hopefullymeet/Hopefullymeet.github.io
        branch: master  # 部署到 'master' 分支
