name: Deploy Hexo Site

on:
  push:
    branches:
      - main  # Assuming your source files are on the 'main' branch
  workflow_dispatch:  # 允许手动触发工作流程
      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'  # Use the Node.js version that matches your development environment

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install Dependencies
      run: npm install

    - name: Build Site
      run: ./node_modules/.bin/hexo generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # The default directory for Hexo static files
